let config = {
  _apiBasicPath: "/mock/",
  _apiUrlSuffix: ".json",
  createFullPath(path) {
    return this._apiBasicPath + path + this._apiUrlSuffix;
  },
  productNameMap: {
    //产品名称的映射表
    new_product: "新手标",
    ttz_product: "天天赚",
    yyz_product: "月月赚",
    jjz_product: "季季赚",
    loan_product: "好采投",
    creditor_product: "债权转让",
    moon: "月满盈",
    rich: "丰收盈",
    glj: "果乐金",
    ced: "车e贷",
    nyd:"农易贷"
  },
  pageNameMap: {
    //组件/页面名称的映射表
    Home: "首页",
    ProductList: "投资",
    MoreProductList: "全部投资项目",
    UserHome: "用户中心",
    GetBackPassword: "找回登录密码",
    SetNewPassword: "设置登录密码",
    "EarnSetIntroduction.new_product": "新手标",
    "EarnSetIntroduction.ttz_product": "天天赚",
    "EarnSetIntroduction.yyz_product": "月月赚",
    "EarnSetIntroduction.jjz_product": "季季赚",
    FixedLoanIntroduction: "好采投",
    CreditorLoanIntroduction: "好采投.转",
    Payment: "支付",
    PurchaseSuccess: "购买成功",
    DailyEarnAppointment: "预约天天赚",
    CouponList: "我的优惠券",
    MessageList: "我的消息",
    Recharge: "充值",
    BindBankCard: "添加银行卡",
    BankCardList: "选择开户银行",
    RealNameAuthentication: "实名认证",
    Withdraw: "提现",
    GetBackDealPassword: "找回交易密码",
    JournalAccount: "资金流水",
    InviteReward: "邀请有礼",
    RewardDetailList: "奖励明细",
    InviteMyFriend: "邀请好友",
    My2DCode: "我的二维码",
    AppSetting: "设置和帮助",
    MyBankCard: "我的银行卡",
    DeleteBankCardConfirm: "删卡确认",
    DeleteCardApplySuccess: "提交成功",
    MyBankCardDetail: "银行卡详情",
    SecurityCenter: "安全中心",
    TotalAccountDetail: "总资产明细",
    DailyEarnCenter: "灵活投资",
    DailyEarnRollOut: "天天赚转出",
    DailyEarnInvestmentRecord: "灵活投资明细",
    RepaymentCalendar: "回款日历",
    FixedLoanCenter: "定期投资",
    FixedLoanInvestmentRecord: "项目直投投资明细",
    CreditorLoanInvestmentRecord: "债权转让投资明细",
    RepaymentSchedule: "投资回款详情",
    AssignmentOfDebt: "债权转让",
    NewbieGuide: "新手指引",
    ServiceAgreement_register: "注册服务协议",
    ServiceAgreement_new_product: "新手标服务协议",
    ServiceAgreement_ttz_product: "天天赚服务协议",
    ServiceAgreement_yyz_product: "月月赚服务协议",
    ServiceAgreement_jjz_product: "季季赚服务协议",
    ServiceAgreement_loan_product: "借款服务协议",
    ServiceAgreement_creditor_product: "债权转让服务协议",
    ServiceAgreement_moon: "月满盈服务协议",
    ServiceAgreement_rich: "丰收盈服务协议",
    AboutUs: "关于我们",
    BannerPageWrapper: "饭米粒理财",
    ZhongJinShortcutPay: "充值",
    OpenZhongJinShortcut: "开通快捷支付",
    RegisterToZXBank: "开通银行存管子账户",
    VerifyCodeForRegisterGuide: "手机验证码",
    AnniversaryCelebration_fruitStory: "水果故事",
    SkipRegisteringZX: "信息确认",
    SecurityIntroduction: "安全保障",
    UserStoryList: "热门推荐",
    ServiceAgreement_risk_announce: "风险提示告知书",
    OpenRedPackage: "领取红包",
    GetRedPackage: "恭喜您",
    richLoanIntroduction: "丰收盈",
    moonLoanIntroduction: "月满盈",
    MoonLoanInvestmentRecord: "月满盈",
    ApplyToQuiteFromMoonLoan: "预约退出",
    MatchLoanOfMoon: "配标详情",
    MatchLoanList: "配标详情",
    AssignDebtRecord: "转让进度",
    VIPProfile: "个人资料",
    MyInviteFriendDetail: "我的邀请",
    ExchangeCoupon: "兑换优惠券",
    AppFeedback: "意见反馈",
    ShareCoupon: "分享优惠礼券",
    RechargeWithBAOFU: "充值",
    SetNewMobilePhoneNo: "修改手机号码",
    AutoPurchaseRule: "自动投标规则",
    ServiceAgreement_autoPurchase: "自动投标授权书",
    InformationDisclosure: "信息披露",
    PlatformSurvey: "平台概况",
    OperationReport: "运营报告",
    ShareholderInfo: "股东信息",
    CompanyQualification: "公司资质",
    CompanyGlories: "公司荣誉",
    OrganizationStructure: "组织架构",
    ManagementTeam: "管理团队",
    DevelopmentHistory: "发展历程",
    ArticlesOfNTLaw: "法律法规",
    AuditReport: "审计报告",
    SeviceAgreement_registerToPABank: "饭米粒理财",
    "RiskAnnounceHint":"风险提示",
    ModifyOrResetDealPWForPABank: "交易密码",
    BankQuotaTable: "银行限额表"
  },
  noNavBarPages: [
    //不需要显示navBar的页面
    "/",
    "Home",
    "UserHome",
    /*"ProductList",*/
    "Register",
    "PurchaseSuccess",
    "AppointmentSuccess",
    "Default",
    "DeleteCardApplySuccess",
    "MyBankCardDetail",
    "MyBankCard",
    "SetDealPassword",
    "SetNewPassword",
    "TotalAccountDetail",
    "SecurityCenter",
    "DailyEarnCenter",
    "DailyEarnRollOutSuccess",
    "DailyEarnInvestmentRecord",
    "EarnSetInvestmentRecord",
    "AssignmentDebtSuccess",
    "InviteMyFriend",
    "RegisterToZXBank",
    "BankCardList",
    "Double11",
    "OpenZXIntroduction",
    "RegisterToZXFailedHint",
    "RegisterToZXSuccessHint",
    "RegisterGuide",
    "Recharge",
    "AnniversaryCelebration",
    "SkipRegisteringZX",
    "ProductList",
    "RealNameAuthentication",
    "BindBankCard",
    "VerifyCodeForRegisterGuide",
    "PlatformData",
    "NewYearCelebration",
    "FixedLoanIntroduction",
    "CreditorLoanIntroduction",
    "SendRedPackage",
    "GetRedPackage",
    "CouponList",
    "OpenRedPackage",
    "ApplyToQuiteFromMoonLoan",
    "QuitFromMoonLoanSuccess",
    "RepaymentSchedule",
    "MoonLoanInvestmentRecord",
    "AllProductEMInvestmentRecord",
    "ServiceAgreement_creditor_product",
    "ServiceAgreement_loan_product",
    "EarnSetIntroduction",
    "NewbieGuide",
    "PresentGoldenApple",
    "registerSuccessHint",
    "ModifyMobilePhone",
    "AutoPurchaseIndex",
    "AutoPurchaseType",
    "AutoPurchaseForm",
    "RegisterToPABank",
    "BankListOfPACG",
    "SearchSubbranchBank",
    "RegisterToPABankFailedHint",
    "RegisterToPABankSuccessHint",
    "WithdrawApplySuccessHint",
    "Withdraw",
    "UpgradeToPABank",
    "RiskEvaluate",
    "BannerPageWrapper",
    "AssignDebtRecord"
  ],
  hasTabBarPages: [
    //需要显示tabBar的页面
    "Home",
    "ProductList",
    "UserHome"
  ],
  needToInterceptPages: [
    //需要进行登录拦截的页面
    "DailyEarnAppointment",
    "Payment",
    "UserHome",
    "ServiceAgreement_loan_product",
    "ServiceAgreement_creditor_product"
  ]
};

export default config;
