var appDispatcher=require("../dispatcher/dispatcher.js");

var UserHOmeAction={
    getInitailDataFromServer (){
        appDispatcher.dispatch({
            actionName:"getInitailDataFromServer_userHome"
        });
    },
    getUserInfoDetail(){
        appDispatcher.dispatch({
            actionName:"getUserInfoDetail"
        });
    },
    getBankCardInfo(){
        appDispatcher.dispatch({
            actionName:"getBankCardInfo"
        });
    },
    recharge(){
        appDispatcher.dispatch({
            actionName:"securityCheck",
            data:{
                operationName:"recharge"
            }
        });
    },
    withdraw(){
        appDispatcher.dispatch({
            actionName:"securityCheck",
            data:{
                operationName:"withdraw"
            }
        });
    },
    extractDailyEarnIncomeCheck(){
        appDispatcher.dispatch({
            actionName:"securityCheck",
            data:{
                operationName:"dailyEarnIncomeExtract"
            }
        })
    },
    rollOutDailyEarnCheck(){
        appDispatcher.dispatch({
            actionName:"securityCheck",
            data:{
                operationName:"dailyEarnRollOut"
            }
        })
    },
    transferDebtCheck(){
        appDispatcher.dispatch({
            actionName:"securityCheck",
            data:{
                operationName:"transferDebt"
            }
        })
    }
};

module.exports=UserHOmeAction;